title: Sample Website for Poetry Collection
description: This is a sample website for publishing a poetry collection using the Leap Day theme.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day